apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secret-store
  target:
    name: platform-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: online-interview/prod
