apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secret-store
  target:
    name: platform-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: online-interview/dev
