apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-interview-dev
resources:
  - ../../base
  - vault-secret-store.yaml
  - external-secret.yaml
  - tls-ingress.yaml
images:
  - {name: ghcr.io/skpandey15/java-ai-mcp-web-ui, digest: sha256:6f6a1396c5061b2fcba268f3041f86062bd2ea05a7f0f34478ebf15463014e33}
  - {name: ghcr.io/skpandey15/java-ai-mcp-interview-orchestrator, digest: sha256:e6ca8882559ce3d4f189b65ac3d18967b8c02ea0d5455fe74bc896dc60b0159f}
  - {name: ghcr.io/skpandey15/java-ai-mcp-ai-service, digest: sha256:cc6f9d4c85a7b3c53b67c90c782cf22cd57d4ef93b8fb9fc6da2a09ec0d3b4d5}
configMapGenerator:
  - name: platform-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=dev
      - APP_ENVIRONMENT=dev
      - CORS_ALLOWED_ORIGINS=https://interview.dev.example.com
      - KEYCLOAK_ISSUER_URI=https://auth.dev.example.com/realms/online-interview
  - name: web-ui-runtime-config
    behavior: replace
    files:
      - config.js=web-ui-config.js
  - name: keycloak-realm
    behavior: replace
    files:
      - online-interview-realm.json
patches:
  - target: {kind: Namespace, name: online-interview}
    patch: |-
      - {op: replace, path: /metadata/name, value: online-interview-dev}
  - path: shared-patch.yaml
  - target: {kind: Deployment, name: keycloak}
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: [start-dev, --import-realm, --health-enabled=true, --hostname=https://auth.dev.example.com, --proxy-headers=xforwarded]
