apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-interview-dev
resources:
  - ../../base
  - external-secret.yaml
images:
  - {name: ghcr.io/skpandey15/java-ai-mcp-web-ui, newTag: sha-b3ac0c34e03ebce5f02f26859d8c58a382646cf9}
  - {name: ghcr.io/skpandey15/java-ai-mcp-interview-orchestrator, newTag: sha-b3ac0c34e03ebce5f02f26859d8c58a382646cf9}
  - {name: ghcr.io/skpandey15/java-ai-mcp-ai-service, newTag: sha-b3ac0c34e03ebce5f02f26859d8c58a382646cf9}
configMapGenerator:
  - name: platform-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=dev
      - APP_ENVIRONMENT=dev
      - CORS_ALLOWED_ORIGINS=https://interview.dev.example.com
      - KEYCLOAK_ISSUER_URI=https://auth.dev.example.com/realms/online-interview
patches:
  - target: {kind: Namespace, name: online-interview}
    patch: |-
      - {op: replace, path: /metadata/name, value: online-interview-dev}
  - path: shared-patch.yaml
