apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-interview-uat
resources:
  - ../../base
  - external-secret.yaml
images:
  - {name: ghcr.io/skpandey15/java-ai-mcp-web-ui, digest: sha256:c4fc6193393548d3db984cf963d7355b581436a8157fffcd4aad02815c26ec29}
  - {name: ghcr.io/skpandey15/java-ai-mcp-interview-orchestrator, digest: sha256:6c0eddd035ac76fd8261188394ea0c41bfd55e5c57d6bbbd5d12999ac64fbe94}
  - {name: ghcr.io/skpandey15/java-ai-mcp-ai-service, digest: sha256:0ecbf3e07c2545dd3c2efefa7f3256dca289f7bdb85d69274f17e0db8bcb1d99}
configMapGenerator:
  - name: platform-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=uat
      - APP_ENVIRONMENT=uat
      - CORS_ALLOWED_ORIGINS=https://interview.uat.example.com
      - KEYCLOAK_ISSUER_URI=https://auth.uat.example.com/realms/online-interview
  - name: web-ui-runtime-config
    behavior: replace
    files:
      - config.js=web-ui-config.js
  - name: keycloak-realm
    behavior: replace
    files:
      - online-interview-realm.json
patches:
  - target: {kind: Namespace, name: online-interview}
    patch: |-
      - {op: replace, path: /metadata/name, value: online-interview-uat}
  - path: shared-patch.yaml
  - target: {kind: Deployment, name: keycloak}
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: [start, --import-realm, --health-enabled=true, --http-enabled=true, --hostname=https://auth.uat.example.com, --proxy-headers=xforwarded]
