apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: vault-local-only
  namespace: vault
spec:
  ipAllowList:
    sourceRange:
      - 127.0.0.0/8
      - ::1/128
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: vault
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: vault-vault-local-only@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - secretName: vault-dev-tls
      hosts:
        - vault.dev.interview.localhost
  rules:
    - host: vault.dev.interview.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
